"""'Add_Posts_Model'

Revision ID: 66256112a11d
Revises: 8e73cda8f021
Create Date: 2023-04-10 18:31:51.566555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66256112a11d'
down_revision = '8e73cda8f021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['poster_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
