"""Add_Posts_Model

Revision ID: 737cd739e4c5
Revises: f87b4dbc335f
Create Date: 2023-04-12 21:09:47.332191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737cd739e4c5'
down_revision = 'f87b4dbc335f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posts_userid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('posts_userid')

    # ### end Alembic commands ###
