"""Change fav_color to ---> Role

Revision ID: 7752afb2a794
Revises: 8862aa0fa127
Create Date: 2023-04-05 23:42:11.450212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7752afb2a794'
down_revision = '8862aa0fa127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=150), nullable=False))
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_color', mysql.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
