"""'Upgrade-Res-DB'

Revision ID: 8862aa0fa127
Revises: d64477da826c
Create Date: 2023-03-31 14:59:40.555747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8862aa0fa127'
down_revision = 'd64477da826c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_date_start', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('selected_date_end', sa.String(length=255), nullable=True))
        batch_op.drop_column('selected_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_date', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('selected_date_end')
        batch_op.drop_column('selected_date_start')

    # ### end Alembic commands ###
