"""Add_Posts_Model

Revision ID: 8954bd6ec50b
Revises: dcd574973d6b
Create Date: 2023-04-11 12:31:24.676081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8954bd6ec50b'
down_revision = 'dcd574973d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('slug')
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('slug', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
