"""Add_Posts_Model

Revision ID: f451edcd2ab4
Revises: d23277b8a7fa
Create Date: 2023-04-12 15:30:54.055217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f451edcd2ab4'
down_revision = 'd23277b8a7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
